/* Procedures de insercao. toda gravacao do app passa por aqui, sem INSERT/UPDATE direto do Delphi. */

CREATE OR ALTER EXCEPTION EX_LOTE_NAO_ENCONTRADO
    'Lote nao encontrado.';
CREATE OR ALTER EXCEPTION EX_QTD_INVALIDA
    'Quantidade informada deve ser maior que zero.';
CREATE OR ALTER EXCEPTION EX_PESO_INVALIDO
    'Peso medio informado deve ser maior que zero.';
CREATE OR ALTER EXCEPTION EX_QTD_PESADA_EXCEDIDA
    'Quantidade pesada excede a quantidade inicial do lote.';
CREATE OR ALTER EXCEPTION EX_MORTALIDADE_EXCEDIDA
    'Mortalidade acumulada excede a quantidade inicial do lote.';

COMMIT;

SET TERM ^ ;

/* Insere a pesagem e atualiza o peso medio geral do lote. */
CREATE OR ALTER PROCEDURE SP_INSERE_PESAGEM (
    I_ID_LOTE            INTEGER,
    I_DATA_PESAGEM       DATE,
    I_PESO_MEDIO         NUMERIC(10,2),
    I_QUANTIDADE_PESADA  INTEGER
)
RETURNS (
    O_ID_PESAGEM         INTEGER,
    O_PESO_MEDIO_GERAL   NUMERIC(10,2)
)
AS
DECLARE VARIABLE V_QTD_INICIAL INTEGER;
BEGIN
    SELECT QUANTIDADE_INICIAL
      FROM TAB_LOTE_AVES
     WHERE ID_LOTE = :I_ID_LOTE
      WITH LOCK
      INTO :V_QTD_INICIAL;

    IF (ROW_COUNT = 0) THEN
        EXCEPTION EX_LOTE_NAO_ENCONTRADO;

    IF (I_QUANTIDADE_PESADA IS NULL OR I_QUANTIDADE_PESADA <= 0) THEN
        EXCEPTION EX_QTD_INVALIDA;

    IF (I_PESO_MEDIO IS NULL OR I_PESO_MEDIO <= 0) THEN
        EXCEPTION EX_PESO_INVALIDO;

    IF (I_QUANTIDADE_PESADA > V_QTD_INICIAL) THEN
        EXCEPTION EX_QTD_PESADA_EXCEDIDA;

    INSERT INTO TAB_PESAGEM
        (ID_LOTE_FK, DATA_PESAGEM, PESO_MEDIO, QUANTIDADE_PESADA)
    VALUES
        (:I_ID_LOTE, :I_DATA_PESAGEM, :I_PESO_MEDIO, :I_QUANTIDADE_PESADA)
    RETURNING ID_PESAGEM INTO :O_ID_PESAGEM;

    SELECT CAST(SUM(CAST(PESO_MEDIO AS DOUBLE PRECISION) * QUANTIDADE_PESADA)
                / SUM(QUANTIDADE_PESADA) AS NUMERIC(10,2))
      FROM TAB_PESAGEM
     WHERE ID_LOTE_FK = :I_ID_LOTE
      INTO :O_PESO_MEDIO_GERAL;

    UPDATE TAB_LOTE_AVES
       SET PESO_MEDIO_GERAL = :O_PESO_MEDIO_GERAL
     WHERE ID_LOTE = :I_ID_LOTE;
END
^

/* Insere a mortalidade e devolve a acumulada + percentual sobre a quantidade inicial, que o app usa no indicador de saude do lote. */
CREATE OR ALTER PROCEDURE SP_INSERE_MORTALIDADE (
    I_ID_LOTE                 INTEGER,
    I_DATA_MORTALIDADE        DATE,
    I_QUANTIDADE_MORTA        INTEGER,
    I_OBSERVACAO              VARCHAR(255)
)
RETURNS (
    O_ID_MORTALIDADE          INTEGER,
    O_MORTALIDADE_ACUMULADA   INTEGER,
    O_PERCENTUAL_MORTALIDADE  NUMERIC(5,2)
)
AS
DECLARE VARIABLE V_QTD_INICIAL INTEGER;
DECLARE VARIABLE V_ACUMULADA_ANTERIOR INTEGER;
BEGIN
    /* trava a linha do lote: duas sessoes lancando ao mesmo tempo nao podem, somadas, passar da quantidade inicial */
    SELECT QUANTIDADE_INICIAL
      FROM TAB_LOTE_AVES
     WHERE ID_LOTE = :I_ID_LOTE
      WITH LOCK
      INTO :V_QTD_INICIAL;

    IF (ROW_COUNT = 0) THEN
        EXCEPTION EX_LOTE_NAO_ENCONTRADO;

    IF (I_QUANTIDADE_MORTA IS NULL OR I_QUANTIDADE_MORTA <= 0) THEN
        EXCEPTION EX_QTD_INVALIDA;

    SELECT COALESCE(SUM(QUANTIDADE_MORTA), 0)
      FROM TAB_MORTALIDADE
     WHERE ID_LOTE_FK = :I_ID_LOTE
      INTO :V_ACUMULADA_ANTERIOR;

    IF (V_ACUMULADA_ANTERIOR + I_QUANTIDADE_MORTA > V_QTD_INICIAL) THEN
        EXCEPTION EX_MORTALIDADE_EXCEDIDA;

    INSERT INTO TAB_MORTALIDADE
        (ID_LOTE_FK, DATA_MORTALIDADE, QUANTIDADE_MORTA, OBSERVACAO)
    VALUES
        (:I_ID_LOTE, :I_DATA_MORTALIDADE, :I_QUANTIDADE_MORTA, :I_OBSERVACAO)
    RETURNING ID_MORTALIDADE INTO :O_ID_MORTALIDADE;

    O_MORTALIDADE_ACUMULADA  = V_ACUMULADA_ANTERIOR + I_QUANTIDADE_MORTA;

    O_PERCENTUAL_MORTALIDADE =
        CAST(CAST(O_MORTALIDADE_ACUMULADA AS DOUBLE PRECISION) * 100
             / V_QTD_INICIAL AS NUMERIC(5,2));
END
^

SET TERM ; ^

COMMIT;
