/* Procedures de consulta (selectable). O grid le via SELECT * FROM SP_... e ja recebe mortalidade acumulada e percentual calculados. */

SET TERM ^ ;

CREATE OR ALTER PROCEDURE SP_LISTA_LOTES
RETURNS (
    O_ID_LOTE                 INTEGER,
    O_DESCRICAO               VARCHAR(100),
    O_DATA_ENTRADA            DATE,
    O_QUANTIDADE_INICIAL      INTEGER,
    O_PESO_MEDIO_GERAL        NUMERIC(10,2),
    O_MORTALIDADE_ACUMULADA   INTEGER,
    O_PERCENTUAL_MORTALIDADE  NUMERIC(5,2)
)
AS
BEGIN
    FOR SELECT L.ID_LOTE, L.DESCRICAO, L.DATA_ENTRADA, L.QUANTIDADE_INICIAL,
               L.PESO_MEDIO_GERAL, COALESCE(SUM(M.QUANTIDADE_MORTA), 0)
          FROM TAB_LOTE_AVES L
          LEFT JOIN TAB_MORTALIDADE M ON M.ID_LOTE_FK = L.ID_LOTE
         GROUP BY L.ID_LOTE, L.DESCRICAO, L.DATA_ENTRADA,
                  L.QUANTIDADE_INICIAL, L.PESO_MEDIO_GERAL
         ORDER BY L.ID_LOTE
          INTO :O_ID_LOTE, :O_DESCRICAO, :O_DATA_ENTRADA, :O_QUANTIDADE_INICIAL,
               :O_PESO_MEDIO_GERAL, :O_MORTALIDADE_ACUMULADA
    DO
    BEGIN
        O_PERCENTUAL_MORTALIDADE =
            CAST(CAST(O_MORTALIDADE_ACUMULADA AS DOUBLE PRECISION) * 100
                 / O_QUANTIDADE_INICIAL AS NUMERIC(5,2));
        SUSPEND;
    END
END
^

CREATE OR ALTER PROCEDURE SP_LISTA_PESAGENS (
    I_ID_LOTE INTEGER
)
RETURNS (
    O_ID_PESAGEM        INTEGER,
    O_DATA_PESAGEM      DATE,
    O_PESO_MEDIO        NUMERIC(10,2),
    O_QUANTIDADE_PESADA INTEGER
)
AS
BEGIN
    FOR SELECT ID_PESAGEM, DATA_PESAGEM, PESO_MEDIO, QUANTIDADE_PESADA
          FROM TAB_PESAGEM
         WHERE ID_LOTE_FK = :I_ID_LOTE
         ORDER BY DATA_PESAGEM DESC, ID_PESAGEM DESC
          INTO :O_ID_PESAGEM, :O_DATA_PESAGEM, :O_PESO_MEDIO, :O_QUANTIDADE_PESADA
    DO
        SUSPEND;
END
^

CREATE OR ALTER PROCEDURE SP_LISTA_MORTALIDADES (
    I_ID_LOTE INTEGER
)
RETURNS (
    O_ID_MORTALIDADE   INTEGER,
    O_DATA_MORTALIDADE DATE,
    O_QUANTIDADE_MORTA INTEGER,
    O_OBSERVACAO       VARCHAR(255)
)
AS
BEGIN
    FOR SELECT ID_MORTALIDADE, DATA_MORTALIDADE, QUANTIDADE_MORTA, OBSERVACAO
          FROM TAB_MORTALIDADE
         WHERE ID_LOTE_FK = :I_ID_LOTE
         ORDER BY DATA_MORTALIDADE DESC, ID_MORTALIDADE DESC
          INTO :O_ID_MORTALIDADE, :O_DATA_MORTALIDADE, :O_QUANTIDADE_MORTA, :O_OBSERVACAO
    DO
        SUSPEND;
END
^

SET TERM ; ^

COMMIT;
